name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: 'Install AWS CLI'
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: 'Terraform Init'
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
        working-directory: terraform/site

      - name: 'Terraform Validate'
        run: terraform validate
        working-directory: terraform/site

      - name: 'Terraform Plan'
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
        working-directory: terraform/site

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
        working-directory: terraform/site

  python_deploy:
    name: 'Python Deploy - AWS Lambda'
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install AWS CLI'
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 'Install Poetry'
        run: |
          pip install poetry
      
      - name: 'Install shared'
        run: |
          cd libs/petshop_support
          poetry install

      - name: 'Deploy'
        run: make fn_deploy_all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
